### ISSUE TITLE
fails when included into a wrapper cookbook 

### ISSUE THREAD

**Issue by anatolijd** [chef-cookbooks/omnibus_updater#49] opened 2014-04-17 18:29 UTC
Hi, Unfortunately, it is not possible to include onmnibus_updater in a wrapper cookbook.

I have a chef_ua::client wrapper cookbook recipe, with the following content:

```
include_recipe "omnibus_updater::default"
include_recipe 'chef-client::config'
include_recipe 'chef-client::service'
```

Chef-client (chef-11.12) run fails with the following error:

```
       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cookbooks/chef_ua/recipes/client.rb
       ================================================================================


       NameError
       ---------
       uninitialized constant Chef::Recipe::OmnibusTrucker


       Cookbook Trace:
       ---------------
         /tmp/kitchen/cookbooks/omnibus_updater/recipes/downloader.rb:8:in `from_file'
         /tmp/kitchen/cookbooks/omnibus_updater/recipes/default.rb:6:in `from_file'
         /tmp/kitchen/cookbooks/chef_ua/recipes/client.rb:23:in `from_file'


       Relevant File Content:
       ----------------------
       /tmp/kitchen/cookbooks/omnibus_updater/recipes/downloader.rb:

         1:  # NOTE: This recipe is here for others that just want the
         2:  # package, not the actual installation (lxc for example)
         3:  
         4:  if(node[:omnibus_updater][:direct_url])
         5:    remote_path = node[:omnibus_updater][:direct_url]
         6:  else
         7:    version = node[:omnibus_updater][:version] || ''
         8>>   remote_path = OmnibusTrucker.url(
         9:      OmnibusTrucker.build_url(node,
        10:        :version => node[:omnibus_updater][:force_latest] ? nil : version.sub(/\-.+$/, ''),
        11:        :prerelease => node[:omnibus_updater][:preview]
        12:      ), node
        13:    )
        14:  end
        15:  
        16:  if(remote_path)
        17:    node.set[:omnibus_updater][:full_url] = remote_path
       [2014-04-17T17:57:12+00:00] ERROR: Running exception handlers
       [2014-04-17T17:57:12+00:00] ERROR: Exception handlers complete
       [2014-04-17T17:57:12+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
 Chef Client failed. 0 resources updated       
       [2014-04-17T17:57:12+00:00] ERROR: uninitialized constant  Chef::Recipe::OmnibusTrucker
       [2014-04-17T17:57:12+00:00] FATAL: Chef::Exceptions::ChildConvergeError:  Chef run process exited unsuccessfully (exit code 1)
```

I've tried to do some Chef::Resource.send(:include, OmnibusTrucker), unfortunately, unsuccessful.

Is it possible to get OmnibusTrucker module changed in a way it does not fail and we can use omnibus_updater in a wrapper cookbook ?

**Comment by mrdimka** [comment] 2015-02-05 08:36
I get the same. I am upgrading from 11.16.4 to 12.0.3.
I get the following when included on a wrapper cookbook or add it as a recipe on a role.

```
==> default: [2015-02-05T00:12:54-08:00] INFO: ruby_block[Omnibus Chef install notifier] sending run action to execute[omnibus_install[chef_12.0.3-1_i386.deb]] (delayed)
==> default: [2015-02-05T00:13:01-08:00] INFO: execute[omnibus_install[chef_12.0.3-1_i386.deb]] ran successfully
==> default: [2015-02-05T00:13:01-08:00] INFO: execute[omnibus_install[chef_12.0.3-1_i386.deb]] sending create action to ruby_block[omnibus chef killer] (immediate)
==> default: [2015-02-05T00:13:01-08:00] ERROR: Running exception handlers
==> default: [2015-02-05T00:13:01-08:00] ERROR: Exception handlers complete
==> default: [2015-02-05T00:13:01-08:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-02-05T00:13:01-08:00] ERROR: cannot load such file -- highline
==> default: [2015-02-05T00:13:01-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```
The funny thing is that chef is updated. But I still get the error.

**Comment by fletchowns** [comment] 2015-06-11 18:06
I'm running into the same issue trying to update from 11.16.2 to 12.3.0. recipe[omnibus_updater] is in the run list for my role.

Did you guys ever find a workaround?

**Comment by fletchowns** [comment] 2015-06-12 23:36
Despite the error & failed converge, 12.3.0 does seem to get installed, and subsequent converges succeed.

**Comment by lamont-granquist** [comment] 2015-06-15 17:55
The problem is likely related to the major upgrade from 11.16.2 to 12.3.0 which includes a bump to rubygems which changed the location of native compiled gem binaries.

Omnibus updater should probably be a bit more strict about what it does and should:

1.  remove the old package
2.  wipe /opt/chef completely (optionally, but likely this should be by default)
3.  install the new package
4.  immediately re-exec itself to start over 

The problem with that last step is that you will skip delayed notifcation and error handlers, the final node.save and all kinds of other stuff that we assume needs to happen with a 'clean' chef-client run, but if you're doing a major version upgrade you can't assume any of that stuff will ultimately be successful, and in the 11->12 upgrade process it isn't.  You wind up with a Chef 11 ruby 1.9.3 and old rubygems process in-memory and Chef 12 and new rubygems binary locations on-disk and you wind up causing a trainwreck later.

**Comment by fletchowns** [comment] 2015-06-15 22:31
@lamont-granquist didn't Hosted Chef do the major version upgrade with this omnibus_updater cookbook? Wouldn't that have failed with the same error?

Should I just use `knife ssh` to update chef on my nodes from 11 to 12 or what?

**Comment by chrisroberts** [comment] 2015-06-16 17:15
The failure is expected and is the main reason for forcing the client to fail out when a new version is installed (since I'm generally running chef-client as a cron job). It attempts to fail out as soon as possible once the installation is complete. The error you see is exactly the reason why. The installation will pull the rug out from under the running process, and because of this we want the process to halt as soon as possible. The next time it starts (service restart, next cron, what ever), it will be using the new installation and thus converge properly. Once an installation has been performed, attempting to complete a full converge from that point will likely be an exercise of frustration.

For my usage, and how I originally structured the cookbook, was to have the updater as the first thing in the run list. This was due to upgrading chef on systems and knowing the running version would not properly converge with the run list it would pull (10 -> 11 upgrade). It's possible to have it at the end of the run, and disable the forced error state, but it should be recognized that any behavior after the new installation will be undefined.

Hope that helps!

**Comment by lamont-granquist** [comment] 2015-06-16 21:12
Yeah I also think we just didn't care on Hosted.  If it fails, run it again.  Its in a cronjob, so no worries.

**Comment by cheeseplus** [comment] 2016-12-23 01:01
Reading the thread this seems to be intended behaviour for this case - closing.

**Closed by cheeseplus** 2016-12-23 01:01 UTC
